# Tensor Manipulation

In [ ]:
# https://www.tensorflow.org/api_guides/python/array_ops
import tensorflow as tf  # tensorflow
import numpy as np  # numpy
import pprint  # pprint
tf.set_random_seed(777)  # 랜덤 시드 설정 for reproducibility
pp = pprint.PrettyPrinter(indent=4)  # pprint 들여 쓰기 4 설정
sess = tf.InteractiveSession()  # 인터랙티브세션 생성

## Simple Array

In [55]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])  # np 배열 t 생성
pp.pprint(t)  # t 배열 출력
print(t.ndim)  # rank 출력
print(t.shape)  # shape 출력
print(t[0], t[1], t[-1])  # t 0번째 값, t 1번째 값, t 마지막 값  
print(t[2:5], t[4:-1])  # t 2번째부터 4번째값, t 4번째부터 마지막-1 위치 값
print(t[:2], t[3:])  # t 처음부터 1번째값, t 3번째부터 마지막 값

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.])
(7,) 1
0.0 1.0 6.0
[ 2.  3.  4.] [ 4.  5.]
[ 0.  1.] [ 3.  4.  5.  6.]


# 2D Array

In [58]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])  # t 배열
pp.pprint(t)  # t 출력
print(t.ndim)  # rank 출력
print(t.shape)  # shape 출력

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])
2
(4, 3)


## Shape, Rank, Axis

In [5]:
t = tf.constant([1,2,3,4])  # t 상수
tf.shape(t).eval()  # shape 출력

array([4], dtype=int32)

In [6]:
t = tf.constant([[1,2], [3,4]])  # t 상수
tf.shape(t).eval()  # shape 출력

array([2, 2], dtype=int32)

In [60]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])  # t 상수
tf.shape(t).eval()  # shape 출력

array([1, 2, 3, 4], dtype=int32)

In [8]:
[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]  # [] 괄호가 4개 열리므로 4차원 (1,2,3,4)

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

## Matmul VS multiply

In [9]:
matrix1 = tf.constant([[3., 3.]])  # (1, 2)
matrix2 = tf.constant([[2.],[2.]])  # (2, 1)
tf.matmul(matrix1, matrix2).eval()  # 행렬곱 결과 1x1

array([[ 12.]], dtype=float32)

In [10]:
(matrix1*matrix2).eval()  # element wise 곱은 각각 원소에 대한 곱셈 계산

array([[ 6.,  6.],
       [ 6.,  6.]], dtype=float32)

## Watch out broadcasting

In [11]:
matrix1 = tf.constant([[3., 3.]])  # (1, 2)
matrix2 = tf.constant([[2.],[2.]])  # (2, 1)
(matrix1+matrix2).eval()  # 덧셈 결과 (2, 2)

array([[ 5.,  5.],
       [ 5.,  5.]], dtype=float32)

In [12]:
matrix1 = tf.constant([[3., 3.]])  # (1, 2)
matrix2 = tf.constant([[2., 2.]])  # (1, 2)
(matrix1+matrix2).eval()  # 덧셈 결과 (1, 2)

array([[ 5.,  5.]], dtype=float32)

## Random values for variable initializations 

In [2]:
tf.random_normal([3]).eval()  # normal 분포의 랜덤값 3개

array([ 2.20866942, -0.73225045,  0.33533147], dtype=float32)

In [3]:
tf.random_uniform([2]).eval()  # uniform 분포의 랜덤값 3개

array([ 0.08186948,  0.42999184], dtype=float32)

In [4]:
tf.random_uniform([2, 3]).eval()  # uniform 분포의 랜덤값 [2, 3]개

array([[ 0.43535876,  0.76933432,  0.65130949],
       [ 0.90863407,  0.06278825,  0.85073185]], dtype=float32)

## Reduce Mean/Sum

In [13]:
tf.reduce_mean([1, 2], axis=0).eval()  # 평균 계산(정수형)

1

In [14]:
x = [[1., 2.],  
     [3., 4.]]
tf.reduce_mean(x).eval()  # 평균 계산(실수형)

2.5

In [15]:
tf.reduce_mean(x, axis=0).eval()  # 세로축 평균 계산

array([ 2.,  3.], dtype=float32)

In [16]:
tf.reduce_mean(x, axis=1).eval()  # 가로축 평균 계산

array([ 1.5,  3.5], dtype=float32)

In [17]:
tf.reduce_mean(x, axis=-1).eval()  # 마지막축 평균 계산

array([ 1.5,  3.5], dtype=float32)

In [18]:
tf.reduce_sum(x).eval()  # 합계

10.0

In [19]:
tf.reduce_sum(x, axis=0).eval()  # 가로축 합계

array([ 4.,  6.], dtype=float32)

In [20]:
tf.reduce_sum(x, axis=-1).eval()  # 마지막축 합계

array([ 3.,  7.], dtype=float32)

In [21]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()  # 마지막축 합계의 평균

5.0

## Argmax with axis

In [22]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()  # 세로축 큰값의 번호

array([1, 0, 0])

In [23]:
tf.argmax(x, axis=1).eval()  # 가로축 큰 값의 번호

array([2, 0])

In [24]:
tf.argmax(x, axis=-1).eval()  # 마지막축 큰 값의 번호

array([2, 0])

## Reshape, squeeze, expand_dims

In [25]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape  # shape 출력 (2, 2, 3)

(2, 2, 3)

In [26]:
tf.reshape(t, shape=[-1, 3]).eval()  # 3기준으로 reshape  

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
tf.reshape(t, shape=[-1, 1, 3]).eval()  # (1, 3) 기준으로 reshape 

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [28]:
tf.squeeze([[0], [1], [2]]).eval()  # 차원 1감소

array([0, 1, 2], dtype=int32)

In [29]:
tf.expand_dims([0, 1, 2], 1).eval()  # 차원 1증가

array([[0],
       [1],
       [2]], dtype=int32)

## One hot

In [30]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval() # 원핫 인코딩

array([[[ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.]],

       [[ 0.,  0.,  1.]],

       [[ 1.,  0.,  0.]]], dtype=float32)

In [31]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)  # 원핫 인코딩
tf.reshape(t, shape=[-1, 3]).eval()  # 3기준으로 reshape

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

## casting

In [32]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()  # 실수를 정수형으로 형변환

array([1, 2, 3, 4], dtype=int32)

In [33]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()  # 불리언을 정수형으로 형변환

array([1, 0, 1, 0], dtype=int32)

## Stack

In [34]:
x = [1, 4]
y = [2, 5]
z = [3, 6]
tf.stack([x, y, z]).eval()  # 첫번째 차원을 따라 (세로로) 쌓기 Pack along first dim.

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [35]:
tf.stack([x, y, z], axis=1).eval()  # 가로로 쌓기

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

## Ones like and Zeros like

In [36]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.ones_like(x).eval()  # 1로 구성된 shape 같은 배열

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [37]:
tf.zeros_like(x).eval()  # 0으로 구성된 shape 같은 배열

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

## Zip


In [38]:
for x, y in zip([1, 2, 3], [4, 5, 6]):  # zip 으로 두 리스트를 묶어서 원소 하나씩 처리
    print(x, y)

1 4
2 5
3 6


In [39]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):  # zip 으로 묶어서 원소 하나씩 처리
    print(x, y, z)

1 4 7
2 5 8
3 6 9


## Transpose

In [40]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])  
pp.pprint(t.shape)  # shape 출력 (2,2,3)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [41]:
t1 = tf.transpose(t, [1, 0, 2])  # 전치행렬시 차원 순열 설정
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


In [42]:
t = tf.transpose(t1, [1, 0, 2])  # 다시 전치행렬시 본래 형태로 돌아옴
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [43]:
t2 = tf.transpose(t, [1, 2, 0])  # 전치행렬시 차원 순열 설정
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

(2, 3, 2)
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])


In [44]:
t = tf.transpose(t2, [2, 0, 1])  # 전치행렬시 차원 순열 설정
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])
